apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tp-node
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: pg_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: pg_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: pg_db
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /data/postgres
              name: postgres-volume
          resources: {}
      volumes:
        - name: postgres-volume
          hostPath:
            path: ""
            type: DirectoryOrCreate
