apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: tp-node
  labels:
    app: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
