apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: tp-node
  name: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1
