apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tp-node
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-volume
          hostPath:
            path: /data/postgres
            type: DirectoryOrCreate
